language: node_js
node_js:
- 10
script:
- yarn test
- yarn lint
jobs:
  include:
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release
env:
  global:
  - secure: RNtDXTPKnuUyoy73u5yINmSUd9lbP8+nB4UdoFtX6lOBQv0eILPtX9nIiZNXMcn7Kf7qk9Ivf5aW3CQku9F5eeFWhLmQKjxp8AXTuJM3tZpaMPnG9dpE2dRRgWRrXQWrZvPNWhYpuIYeeo35Mg9S11/vL4O2GFRUfLajKMn/sS02GLf4tRVoSaraQVCuZIsXnCSUoJ5U497QUu+eVXFyI/VApxEIsL/DMxAk+fMdE7YtODD7pRG/6EjytOGzDV/N6JNu7oK0185XKis9Fhb6G4/uQKW3tXaWThk9fDw27seEfEv8UbnH/Ipav9HfJ8+crFYZ+sRxacX69kmkEjCPOFBnMU8b7QUU17QrZWogOlFbRdH0d8mItk1BB0PmVwJ7EQrTXhT7yGjEakKjEbbyRMs2AR2lHfTa6ewQ504oLQxPvo9r5SGoYbHwB04OS7ewGNPuqLNwPPjVgXW2XjKhMIZ5SDiObswAHTHenC0qAaBOZiqikwpNqDlrnevvIohXoi7Q+Jzk8ZiGG7l5TCDBAkYt9x77TZEoSEipDu6s8OTpK/KLmJrbrJ9R/kYyizwDjswf/iL/H5RgbVhSPSleRQxShhs2Wj1I2ybdKrZVodDqrB1qQosfQ6SVrbbxkAULjgtGU84mzH4L0DmVBhgIJtb+fPi0+QNOeICdyA8S/pU=
  - secure: vWmEYRbzboFV9fjUuteNvAbbDhX0rwa5sYlaqob6NkU5wJYbFCqCLkUJNe40TCob90W73n7oMJnQmV91oueN1rsk30bhMfaYKPqC2qL4Y7ovexo9aGFTnL4Qt4F60/HjgoT9s+u8HR4njwmSVNCKFrI5c3rYHcAGINn5Wg5QqUgEI8D21xYV58sUtsXIYPThFDLDmWVPULODyaO6CNQPGcSHnKqtCpEU11GQJCa1dzZzQRA7tjD14ysP82oL95cvJZwk/0W3M3oUujNoh4gqTOpqqVWaix2zxp29ctbA/E22pKMKsX+aWJVpzzib9TUpTvR7JVKZCJ9stLvBMp/xdaHQ7S2jLix12qnQmT0WrnjEdCu+EKejALU6T4Dvt+QMzg02zlCCovFF0DMlb0dgSYiWKxkjcP0cE0JEc6fTWKBJ4p8xUa1FpQIlw3vnpAfUyF1TkhMJ5DNdB71J59wV0M05gbbyrZ1j0mymvZ0DaQsU9coanZkpnx1yE41SFAGyntzzcueZSJbu/33QNYF3sCc2F8ToLxRhcwxe42Mrrf/xIJLWGNFEclbk9cy6N+iTtX5ZTNSiiVbh7wf2hOilr0jxq/t+HNtwZKGhHWwQJ3B8XDDcYwTUHIppGO5f9iRwkTLJN6jyQ33ReJzrvF+rPgSIw9a/aBTJjLo86iL24fI=
