language: node_js

node_js:
  - 10

script:
  - yarn test
  - yarn lint

before_deploy:
  - yarn tsc
  - cp package.json ./dist/
  - cp README.md ./dist/
  - cp CHANGELOG.md ./dist/

jobs:
  include:
  - stage: release
    node_js: 10
    deploy:
      provider: script
      skip_cleanup: true
      script:
        - npx semantic-release

env:
  global:
  - secure: RNtDXTPKnuUyoy73u5yINmSUd9lbP8+nB4UdoFtX6lOBQv0eILPtX9nIiZNXMcn7Kf7qk9Ivf5aW3CQku9F5eeFWhLmQKjxp8AXTuJM3tZpaMPnG9dpE2dRRgWRrXQWrZvPNWhYpuIYeeo35Mg9S11/vL4O2GFRUfLajKMn/sS02GLf4tRVoSaraQVCuZIsXnCSUoJ5U497QUu+eVXFyI/VApxEIsL/DMxAk+fMdE7YtODD7pRG/6EjytOGzDV/N6JNu7oK0185XKis9Fhb6G4/uQKW3tXaWThk9fDw27seEfEv8UbnH/Ipav9HfJ8+crFYZ+sRxacX69kmkEjCPOFBnMU8b7QUU17QrZWogOlFbRdH0d8mItk1BB0PmVwJ7EQrTXhT7yGjEakKjEbbyRMs2AR2lHfTa6ewQ504oLQxPvo9r5SGoYbHwB04OS7ewGNPuqLNwPPjVgXW2XjKhMIZ5SDiObswAHTHenC0qAaBOZiqikwpNqDlrnevvIohXoi7Q+Jzk8ZiGG7l5TCDBAkYt9x77TZEoSEipDu6s8OTpK/KLmJrbrJ9R/kYyizwDjswf/iL/H5RgbVhSPSleRQxShhs2Wj1I2ybdKrZVodDqrB1qQosfQ6SVrbbxkAULjgtGU84mzH4L0DmVBhgIJtb+fPi0+QNOeICdyA8S/pU=
  - secure: c+2ZcK9EA3ToXzYPym/QfTA6u0kNNj2zGk4uURvTYHGe6D7TuP5FJrG3WGb2I0M+xjoe/U/ztDpVL8H226eN2wMyPqXSpVY0bylBNBqZhno9GCKYnByR1DUnH0IuO3tCChMNgHvjerQkG7LZ0lysrIFoiyciTk++Iy//nyyr/+/rWETKYxK+aBaoTsQ4odOivD98s7oRM95r83JG28eFFrCrkeytKW6iCa31KuUBrksc7VTRboGEV+AX5UPFyk2Hb9XwGDCiZJNmVB8248W4TwNFdcg3mLi//z9wMN6dtfm/BgD4FxX5ZSHvYeasNZUEiOzDpRxMRYRUS3r8/ztmup0yqgFx42559BL5UCm49QayUJpGOFquFTXxNNXBkqL/ipppCwUv/TpGDDtfvJyyMc+dVQNenBFlcJb8uGvBMzR68JLUmDQqaPltzJs9th6VnxXnadMB+lbY3hLovalmLYWmyN/TRAGK0DBHojPi2YPLtTPODbFFvTpzrjU4r6m4k2p/LLrCjp6IUaQng4hv7vAlqNvsxRDiVB5s4tt9+QnAZ1PeKpUaVGmD5K7oLnuU6QIBoXRIASZ0hZR9LLrrHk7N2Hha1kOn7uT77pbwyZIy50yVxUVllMO5Rc1V7E+O04r+xkFpaDwNGOhY9Wsp/7N8LwKgRx4hf1N7HlQsf8Q=
